seed: 1
solver_device: "cpu"

num_poses: 1024
dataset_size: 256 

inner_optim:
  optimizer_cls: GaussNewton
  solver: sparse
  max_iters: 10 
  step_size: 1
  verbose: true
  reg_w: 1e-3

hydra:
  run:
    dir: examples/outputs/pgo/pose_graph_cube
  sweep:
    dir: examples/outputs/pgo/pose_graph_cube
