seed: 0
save_all: true

dataset_name: "rectangle-pushing-corners-keypoints"
sdf_name: "rect"

episode_length: 25
max_steps: 100
max_episodes: 100  # if split = true, actual number might be slightly larger
split_episodes: true

inner_optim:
  max_iters: 10
  optimizer: GaussNewton
  reg_w: 0
  backward_mode: IMPLICIT
  backward_num_iterations: 2 # only needed by TRUNCATED backward mode
  dlm_epsilon: None
  force_implicit_by_epoch: 10000
  step_size: 1.0
  keep_step_size: true
  force_max_iters: false
  val_iters: 50
  use_batches: true

train:
  # options: "weights_only" or "weights_and_measurement_nn"
  mode: "weights_and_measurement_nn"
  batch_size: 8
  num_epochs: 200
  lr: 1e-4
  optimizer: "adam" # "adam", "rmsprop"
  lr_decay: 1.0

# 0: disc, 1: rect-edges, 2: rect-corners, 3: ellip
class_label: 2
num_classes: 4

shape:
  rect_len_x: 0.2363
  rect_len_y: 0.1579

tactile_cost:
    # window size (min, max, step) over which to add pairwise costs
    min_win_mf: 10
    max_win_mf: 40
    step_win_mf: 5
    init_pretrained_model: True

options:
  vis_traj: True

hydra:
  run: 
    dir: examples/outputs